/*
    This file is part of darktable,
    Copyright (C) 2026 darktable developers.

    darktable is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    darktable is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with darktable.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Printable calibration charts.
 *
 * A grid of straight lines, not a chessboard: common/lens_grid.h traces
 * each chart line as a continuous curve and intersects traced curves for
 * lattice points, rather than looking for chessboard corners. Any square
 * grid works at any print size -- the solver is handed the chart's *cell
 * aspect ratio*, never a physical dimension, and every chart here has
 * square cells -- but a chart shaped like the sensor being calibrated
 * fills the frame edge to edge, which matters most exactly at the
 * corners the whole measurement exists to correct.
 *
 * Generated by tools/make_charts.py in the lensfit repo (vector PDF, no
 * dependency beyond the interpreter) and installed to
 * <datadir>/charts alongside the shipped lens database. Opened with
 * whatever the system already uses for a PDF rather than rendered here --
 * there is no reason to carry a PDF viewer for something this occasional.
 *
 * One sheet, not one per ratio: the grid is sized for 16:9, with a dashed
 * guide printed on it for every other common ratio, nested about the same
 * centre -- narrower ratios crop width, wider ones crop height, since
 * nothing can extend past the sheet's own edge. Whichever guide is framed
 * edge to edge in the viewfinder gets the same corner coverage a chart
 * shaped just for that ratio would.
 */

#include "common/darktable.h"
#include "common/file_location.h"
#include "control/control.h"
#include "gui/accelerators.h"
#include "gui/gtk.h"
#include "libs/lens_calib_common.h"
#include "libs/lib.h"
#include "libs/lib_api.h"
#include "views/view.h"

DT_MODULE(1)

const char *name(dt_lib_module_t *self)
{
  return _("info");
}

dt_view_type_flags_t views(dt_lib_module_t *self)
{
  return DT_VIEW_LENS_CALIB;
}

uint32_t container(dt_lib_module_t *self)
{
  return DT_UI_CONTAINER_PANEL_RIGHT_CENTER;
}

int position(const dt_lib_module_t *self)
{
  // lowest of the lensfit panels, so it sits at the very bottom -- see the
  // note in task.md about position() running backwards from intuition
  return 50;
}

static void _chart_clicked(GtkWidget *w, dt_lib_module_t *self)
{
  char datadir[PATH_MAX] = { 0 };
  dt_loc_get_datadir(datadir, sizeof(datadir));

  gchar *path = g_build_filename(datadir, "charts",
                                 "lensfit-chart-unified.pdf", NULL);

  if(!g_file_test(path, G_FILE_TEST_IS_REGULAR))
  {
    dt_control_log(_("chart not found -- this darktable was not built with "
                     "the lensfit charts installed"));
    g_free(path);
    return;
  }

  gchar *uri = g_filename_to_uri(path, NULL, NULL);
  if(uri)
  {
    dt_open_url(uri);
    g_free(uri);
  }
  g_free(path);
}

void gui_init(dt_lib_module_t *self)
{
  self->data = NULL;
  self->widget = dt_gui_vbox();

  GtkWidget *blurb = gtk_label_new(
    _("a printed grid to photograph for the chart panel above.\n"
      "one sheet covers every common ratio: it is sized for 16:9, with a\n"
      "dashed guide on it for each other ratio, all sharing the same\n"
      "centre. frame so the guide matching your sensor fills the\n"
      "viewfinder edge to edge -- the rest of the sheet does not need to\n"
      "be in shot. print at any size: only the proportions matter, not\n"
      "the physical dimensions."));
  gtk_label_set_line_wrap(GTK_LABEL(blurb), TRUE);
  gtk_label_set_xalign(GTK_LABEL(blurb), 0.0);
  dt_gui_box_add(self->widget, blurb);

  GtkWidget *btn = dt_action_button_new
    (self, _("open chart"), _chart_clicked, self,
     _("open the calibration chart with your PDF viewer, to print it"), 0,
     (GdkModifierType)0);
  dt_gui_box_add(self->widget, btn);
}

void gui_cleanup(dt_lib_module_t *self)
{
}

// clang-format off
// modelines: These editor modelines have been set for all relevant files by tools/update_modelines.py
// vim: shiftwidth=2 expandtab tabstop=2 cindent
// kate: tab-indents: off; indent-width 2; replace-tabs on; indent-mode cstyle; remove-trailing-spaces modified;
// clang-format on
