/*
    This file is part of darktable,
    Copyright (C) 2026 darktable developers.

    darktable is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    darktable is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with darktable.  If not, see <http://www.gnu.org/licenses/>.
*/

/* Printable calibration charts.
 *
 * A grid of straight lines, not a chessboard: common/lens_grid.h traces
 * each chart line as a continuous curve and intersects traced curves for
 * lattice points, rather than looking for chessboard corners. Any square
 * grid works at any print size -- the solver is handed the chart's *cell
 * aspect ratio*, never a physical dimension, and every chart here has
 * square cells -- but a chart shaped like the sensor being calibrated
 * fills the frame edge to edge, which matters most exactly at the
 * corners the whole measurement exists to correct.
 *
 * Generated by tools/make_charts.py in the lensfit repo (vector PDF, no
 * dependency beyond the interpreter) and installed to
 * <datadir>/charts alongside the shipped lens database. Opened with
 * whatever the system already uses for a PDF rather than rendered here --
 * there is no reason to carry a PDF viewer for something this occasional.
 */

#include "common/darktable.h"
#include "common/file_location.h"
#include "control/control.h"
#include "gui/accelerators.h"
#include "gui/gtk.h"
#include "libs/lens_calib_common.h"
#include "libs/lib.h"
#include "libs/lib_api.h"
#include "views/view.h"

DT_MODULE(1)

// name, aspect ratio label as shown to the user
static const char *const _charts[][2] = {
  { "1x1",    "1:1" },
  { "4x3",    "4:3" },
  { "3x2",    "3:2" },
  { "16x9",   "16:9" },
  { "2.39x1", "2.39:1 (scope)" },
};

const char *name(dt_lib_module_t *self)
{
  return _("info");
}

dt_view_type_flags_t views(dt_lib_module_t *self)
{
  return DT_VIEW_LENS_CALIB;
}

uint32_t container(dt_lib_module_t *self)
{
  return DT_UI_CONTAINER_PANEL_RIGHT_CENTER;
}

int position(const dt_lib_module_t *self)
{
  // lowest of the lensfit panels, so it sits at the very bottom -- see the
  // note in task.md about position() running backwards from intuition
  return 50;
}

static void _chart_clicked(GtkWidget *w, dt_lib_module_t *self)
{
  const char *stem = g_object_get_data(G_OBJECT(w), "chart-stem");
  if(!stem) return;

  char datadir[PATH_MAX] = { 0 };
  dt_loc_get_datadir(datadir, sizeof(datadir));

  gchar *path = g_build_filename(datadir, "charts", stem, NULL);

  if(!g_file_test(path, G_FILE_TEST_IS_REGULAR))
  {
    dt_control_log(_("chart not found -- this darktable was not built with "
                     "the lensfit charts installed"));
    g_free(path);
    return;
  }

  gchar *uri = g_filename_to_uri(path, NULL, NULL);
  if(uri)
  {
    dt_open_url(uri);
    g_free(uri);
  }
  g_free(path);
}

void gui_init(dt_lib_module_t *self)
{
  self->data = NULL;
  self->widget = dt_gui_vbox();

  GtkWidget *blurb = gtk_label_new(
    _("a printed grid to photograph for the chart panel above.\n"
      "any of these works at any focal length or sensor size -- pick\n"
      "the one shaped closest to what you are shooting, so it fills\n"
      "the frame edge to edge. print at any size: only the proportions\n"
      "matter, not the physical dimensions."));
  gtk_label_set_line_wrap(GTK_LABEL(blurb), TRUE);
  gtk_label_set_xalign(GTK_LABEL(blurb), 0.0);
  dt_gui_box_add(self->widget, blurb);

  for(size_t i = 0; i < G_N_ELEMENTS(_charts); i++)
  {
    const char *stem = _charts[i][0];
    const char *label = _charts[i][1];

    gchar *filename = g_strdup_printf("lensfit-chart-%s.pdf", stem);
    gchar *button_label = g_strdup_printf(_("chart %s"), label);

    GtkWidget *btn = dt_action_button_new
      (self, button_label, _chart_clicked, self,
       _("open this chart with your PDF viewer, to print it"), 0,
       (GdkModifierType)0);
    g_object_set_data_full(G_OBJECT(btn), "chart-stem", filename, g_free);
    dt_gui_box_add(self->widget, btn);

    g_free(button_label);
  }
}

void gui_cleanup(dt_lib_module_t *self)
{
}

// clang-format off
// modelines: These editor modelines have been set for all relevant files by tools/update_modelines.py
// vim: shiftwidth=2 expandtab tabstop=2 cindent
// kate: tab-indents: off; indent-width 2; replace-tabs on; indent-mode cstyle; remove-trailing-spaces modified;
// clang-format on
